laboratorio/urls.py
from django.contrib import admin
from django.urls import path, include # Importamos include para incluir las urls de la aplicación resultados
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls), # Url para el panel de administración de Django
    path('', include('resultados.urls')), # Url para la aplicación de resultados
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resultados/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetView

# Nuestras url's
urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('login/', views.signin, name='login'),
    path('register/', views.register, name='register'),
    path('bienvenido/', views.bienvenido, name='bienvenido'),
    path('servicios/', views.servicios, name='servicios'),
    path('eliminar-examen/<int:pk>/',
         views.eliminar_examen, name='eliminar_examen'),
    path('logout/', views.signout, name='logout'),
    path('usuarios/', views.listar_usuarios, name='listar_usuarios'),
    path('crear-usuario/', views.crear_usuario, name='crear_usuario'),
    path('usuarios/editar/<int:pk>/', views.editar_usuario, name='editar_usuario'),
    path('usuarios/eliminar/<int:pk>/',
         views.eliminar_usuario, name='eliminar_usuario'),
    path('examenes/', views.listar_examenes, name='listar_examenes'),
    path('crear-examen/', views.crear_examen, name='crear_examen'),
    path('editar_examen/<int:id>/', views.editar_examen, name='editar_examen'),
    path('eliminar_examen/<int:id>/',
         views.eliminar_examen_permanente, name='eliminar_examen_permanente'),
    path('listar_tipos_examen/', views.listar_tipos_examen,
         name='listar_tipos_examen'),
    path('crear-tipo-examen/', views.crear_tipo_examen, name='crear_tipo_examen'),
    path('editar_tipo_examen/<int:id>/',
         views.editar_tipo_de_examen, name='editar_tipo_de_examen'),
    path('eliminar_tipo_examen/<int:id>/',
         views.eliminar_tipo_de_examen, name='eliminar_tipo_de_examen'),
    path('reporte-mensual/', views.generar_reporte_mensual_pdf,
         name='generar_reporte_mensual_pdf'),
    path('miperfil/', views.perfil, name='perfil'),
    path('eliminar_cuenta/', views.eliminar_cuenta, name='eliminar_cuenta'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

resultados/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

# UserManager personalizado (eliminamos username y usamos email como identificador único)


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("El usuario debe tener un email")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("El superusuario debe tener is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("El superusuario debe tener is_superuser=True.")

        return self.create_user(email, password, **extra_fields)

# Modelo de usuario personalizado


class CustomUser(AbstractUser):
    username = None  # Eliminamos el campo de username
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()  # Usamos el UserManager personalizado

    def __str__(self):
        return self.email

# Tipo de examen


class TipoExamen(models.Model):
    nombre = models.CharField(max_length=255, unique=True)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.nombre}"

# Resultados médicos


class MedicalResult(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    tipoExamen = models.ForeignKey(TipoExamen, on_delete=models.CASCADE)
    examen_Image = models.ImageField(
        upload_to='examenes/', blank=True, null=True)
    observaciones = models.TextField(blank=True, null=True)
    eliminado = models.BooleanField(default=False)
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.tipoExamen.nombre} - {self.user.email}"  # pylint: disable=no-member

resultados/views.py
from xhtml2pdf import pisa
from django.shortcuts import render, redirect
from .forms import CustomUserForm
from .forms import MedicalResultForm
from .forms import TipoExamenForm
from .forms import CustomUserEditWithPasswordForm
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q
from .models import MedicalResult
from .models import TipoExamen
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.core.paginator import Paginator
from django.core.mail import EmailMultiAlternatives
from fpdf import FPDF
import os
from django.conf import settings
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth.views import PasswordResetView

User = get_user_model()  # Obtiene el modelo de usuario actual


def inicio(request):  # Vista de inicio
    return render(request, 'index.html')


def register(request):  # Vista de registro
    if request.method == "POST":
        form = CustomUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()
            enviar_correo_bienvenida(user)
            return redirect('login')
    else:
        form = CustomUserForm()

    # Volver a renderizar la página con los errores visibles
    return render(request, 'register.html', {'form': form})


def signin(request):  # Vista de inicio de sesión

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            try:
                # Buscar usuario por email
                user = User.objects.get(email=email)
                # Autenticar con su username
                user = authenticate(
                    request, username=email, password=password)
            except User.DoesNotExist:
                user = None

            if user is not None:
                login(request, user)
                return redirect("bienvenido")
            else:
                messages.error(request, "Correo o contraseña incorrectos.")
        else:
            messages.error(request, "Error en el formulario.")
    else:
        form = AuthenticationForm()

    return render(request, "login.html", {"form": form})




@login_required
def bienvenido(request):  # Vista de bienvenida
    resultados = MedicalResult.objects.filter(
        user=request.user, eliminado=False)
    return render(request, 'cliente_vista.html', {'resultados': resultados})


@login_required
def perfil(request):
    user = request.user
    # Contar exámenes del usuario (excluyendo eliminados si quieres)
    total_examenes = MedicalResult.objects.filter(user=user, eliminado=False).count()

    context = {
        'user': user,
        'total_examenes': total_examenes,
    }
    return render(request, 'perfil.html', context)

@login_required
def eliminar_cuenta(request):
    if request.method == 'POST':
        user = request.user
        logout(request)  # Cierra sesión antes de eliminar
        user.delete()    # Elimina el usuario
        messages.success(request, 'Tu cuenta ha sido eliminada.')
        return redirect('inicio')  # Cambia 'home' por la url de tu página principal
    else:
        return redirect('perfil')


def signout(request):  # Vista de cierre de sesión
    logout(request)
    return redirect('inicio')


def es_admin(user):  # Verifica si el usuario es administrador
    return user.is_authenticated and user.is_staff


def enviar_correo_bienvenida(usuario):
    asunto = "Bienvenido a Divina Misericordia"
    from_email = "laboratoriodivinamisericordia2@gmail.com"
    to = usuario.email

    contexto = {
        "nombre": usuario.first_name,
        "logo_url": "{% static 'app2/images/logo.png' %}",
    }

    html_content = render_to_string("correo_bienvenida.html", contexto)
    text_content = f"Hola {usuario.first_name}, gracias por registrarte en nuestro sistema."

    msg = EmailMultiAlternatives(asunto, text_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset.html'
    email_template_name = 'registration/password_reset_email.html'  # Tu template HTML
    subject_template_name = 'registration/password_reset_subject.txt'  # Un template para el asunto, sólo texto plano

    def form_valid(self, form):
        """
        Cuando el formulario es válido, enviamos el email con HTML adjunto.
        """
        opts = {
            'use_https': self.request.is_secure(),
            'from_email': None,
            'email_template_name': self.email_template_name,
            'subject_template_name': self.subject_template_name,
            'request': self.request,
            'html_email_template_name': self.email_template_name,
        }
        # El método send_mail envía el correo
        form.save(**opts)
        return super().form_valid(form)




def servicios(request):  # Vista de servicios
    return render(request, 'servicios.html')


@login_required
def eliminar_examen(request, pk):  # Endpoint para eliminar un examen desde el cliente
    examen = get_object_or_404(MedicalResult, pk=pk, user=request.user)
    examen.eliminado = True
    examen.save()
    return redirect('bienvenido')


@login_required
@user_passes_test(es_admin)
def listar_usuarios(request):
    query = request.GET.get("q", "").strip()

    if query:
        usuarios = User.objects.filter(
            Q(first_name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(email__icontains=query)
        )
    else:
        usuarios = User.objects.all()

    # Ordenar para que la paginación sea consistente
    usuarios = usuarios.order_by("first_name", "last_name")

    # PAGINACIÓN: 10 usuarios por página
    paginator = Paginator(usuarios, 1)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        "listar_usuarios.html",
        {"page_obj": page_obj, "query": query}
    )


@login_required
@user_passes_test(es_admin)
def crear_usuario(request):
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            enviar_correo_bienvenida(user)
            messages.success(request, "Usuario creado exitosamente.")
            return redirect('crear_usuario')
        else:
            messages.error(request, "Por favor corrige los errores.")
    else:
        form = CustomUserForm()
    return render(request, 'crear_usuario.html', {'form': form})


@login_required
@user_passes_test(es_admin)
def editar_usuario(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = CustomUserEditWithPasswordForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            new_password = form.cleaned_data.get("password1")
            if new_password:
                user.set_password(new_password)
            user.save()
            messages.success(request, "Usuario actualizado exitosamente.")
            return redirect('listar_usuarios')
        else:
            messages.error(request, "Corrige los errores.")
    else:
        form = CustomUserEditWithPasswordForm(instance=user)
    return render(request, 'editar_usuario.html', {'form': form, 'usuario': user})


@login_required
@user_passes_test(es_admin)
def eliminar_usuario(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.delete()
        messages.success(request, "Usuario eliminado correctamente.")
        return redirect('listar_usuarios')


@login_required
@user_passes_test(es_admin)
def listar_examenes(request):
    query = request.GET.get('q', '').strip()

    # Solo mostrar los examenes que no están eliminados
    examenes = MedicalResult.objects.filter(eliminado=False)

    if query:
        examenes = examenes.filter(
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query) |
            Q(user__email__icontains=query) |
            Q(tipoExamen__nombre__icontains=query) |
            Q(fecha__icontains=query)
        )

    return render(request, 'listar_examenes.html', {
        'examenes': examenes,
        'query': query
    })


@login_required
@user_passes_test(es_admin)
def crear_examen(request):
    if request.method == 'POST':
        form = MedicalResultForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Examen médico creado exitosamente.")
            return redirect('crear_examen')
        else:
            messages.error(request, "Corrige los errores en el formulario.")
    else:
        form = MedicalResultForm()
    return render(request, 'crear_examen.html', {'form': form})


@login_required
@user_passes_test(es_admin)
def editar_examen(request, id):
    examen = get_object_or_404(MedicalResult, id=id)

    if request.method == 'POST':
        form = MedicalResultForm(request.POST, request.FILES, instance=examen)
        if form.is_valid():
            form.save()
            return redirect('listar_examenes')
    else:
        form = MedicalResultForm(instance=examen)

    return render(request, 'editar_examen.html', {'form': form, 'examen': examen})


@login_required
@user_passes_test(es_admin)

resultados/templates/correo_bienvenida.html
<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f6f8fa;
            color: #333333;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .logo {
            max-width: 150px;
        }

        .content {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
        }

        .button {
            display: inline-block;
            margin-top: 15px;
            padding: 10px 15px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <div class="header">
        <img src="{{ logo_url }}" alt="Logo Divina Misericordia" class="logo" />
    </div>
    <div class="content">
        <h2>Hola {{ nombre }},</h2>
        <p>Gracias por registrarte en Divina Misericordia.</p>
        <p>Estamos muy contentos de tenerte con nosotros.</p>
        <a href="{% url 'bienvenido' %}" class="button">Iniciar sesión</a>
    </div>
</body>

</html>

resultados/templates/crear_examen.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <script>
        (function () {
            let savedTheme = localStorage.getItem("theme") || "auto";
            document.documentElement.setAttribute("data-bs-theme", savedTheme);
        })();
    </script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mis Exámenes - Divina Misericordia</title>
    <link rel="icon" href="{% static 'app2/images/favicon.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

    <style>
        html,
        body {
            transition: background-color 0.3s, color 0.3s;
            height: 100%;
            margin: 0;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;

        }

        main {
            flex: 1;
        }

        .card img {
            height: 140px;
            object-fit: cover;
        }

        .card-body {
            padding: 0.75rem;
            font-size: 0.9rem;
        }

        .card-title {
            font-size: 1rem;
        }

        .card-footer {
            padding: 0.5rem;
        }

        h2 {
            font-size: 1.6rem;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary navbar-dark" style="--bs-bg-opacity: .7;">
            <div class="container">
                <a class="navbar-brand d-flex align-items-center" href="{% url 'bienvenido' %}">
                    <img src="{% static 'app2/images/logo.png' %}" alt="Logo" width="130" height="64" class="me-2">
                    <span>Divina Misericordia</span>
                </a>

                <!-- Botón hamburguesa para pantallas pequeñas -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
                    aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Contenido colapsable -->
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'perfil' %}">Mi perfil</a>
                        </li>
                        {% if user.is_staff %}
                        <a href="{% url 'generar_reporte_mensual_pdf' %}" class="btn btn-primary" target="_blank">
                            Generar Reporte Mensual
                        </a>
                        <li class="nav-item dropdown">
                            <button class="nav-link dropdown-toggle btn btn-link" id="crearDropdown"
                                data-bs-toggle="dropdown" aria-expanded="false" type="button">
                                <i class="bi bi-list"></i> Consultar
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="crearDropdown">
                                <li><a class="dropdown-item" href="{% url 'listar_usuarios' %}">Usuarios</a></li>
                                <li><a class="dropdown-item" href="{% url 'listar_examenes' %}">Examen</a></li>
                                <li><a class="dropdown-item" href="{% url 'listar_tipos_examen' %}">Tipo Examen</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <button class="nav-link dropdown-toggle btn btn-link" id="crearDropdown"
                                data-bs-toggle="dropdown" aria-expanded="false" type="button">
                                <i class="bi bi-list"></i> Crear
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="crearDropdown">
                                <li><a class="dropdown-item" href="{% url 'crear_usuario' %}">Usuario</a></li>
                                <li><a class="dropdown-item" href="{% url 'crear_examen' %}">Examen</a></li>
                                <li><a class="dropdown-item" href="{% url 'crear_tipo_examen' %}">Tipo Examen</a></li>
                            </ul>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    {% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <main>
        <div class="container py-5" style="max-width: 600px;">
            <div class="card shadow p-4">
                <h2 class="mb-4 text-center">Registrar Examen Médico</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="id_user" class="form-label d-block text-start">Correo del Paciente</label>
                        {{ form.user }}
                        {% if form.user.errors %}
                        <div class="text-danger small mt-1">
                            {{ form.user.errors.0 }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="id_tipoExamen" class="form-label d-block text-start">Tipo de Examen</label>
                        {{ form.tipoExamen }}
                    </div>

                    <div class="mb-3">
                        <label for="id_examen_Image" class="form-label d-block text-start">Imagen del Examen</label>
                        {{ form.examen_Image }}
                        {% if form.examen_Image.errors %}
                        <div class="text-danger small mt-1">
                            {{ form.examen_Image.errors.0 }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="id_observaciones" class="form-label d-block text-start">Observaciones</label>
                        {{ form.observaciones }}
                    </div>

                    <div class="mt-4 text-center">
                        <button type="submit" class="btn btn-primary px-4">Guardar Examen</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="dropdown position-fixed z-3 bottom-0 end-0 me-3 mb-3">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="themeToggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                <span id="themeIcon"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#" data-theme="light">
                        <i class="bi bi-brightness-high"></i> Claro
                    </a></li>
                <li><a class="dropdown-item" href="#" data-theme="dark">
                        <i class="bi bi-moon"></i> Oscuro
                    </a></li>
            </ul>
        </div>
    </main>





    <footer class="bg-primary mt-5" style="--bs-bg-opacity:.7;">
        <div class="container mt-3">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-5 ">
                <div class="col d-flex flex-column justify-content-center align-items-center">
                    <img class="d-block mx-auto" src="{% static 'app2/images/logo.png' %}" width="130" height="64"
                        alt="">
                    <p class="fs-4 text-white text-center">
                        Divina Misericordia
                    <p>
                </div>
                <div class="col d-flex flex-column justify-content-center align-items-center">
                    <a class="text-decoration-none" target="_blank"
                        href="https://www.instagram.com/lab.divinamisericordia/">
                        <p class="text-white text-center">
                            <i class="bi bi-instagram"></i>
                            Visita nuestro Instagram
                        </p>
                    </a>
                    <a class="text-decoration-none" target="_blank"
                        href="https://api.whatsapp.com/send?phone=584160721099&text=Hola%20estoy%20interesado%20en%20un%20examen">
                        <p class="text-white text-center">
                            <i class="bi bi-whatsapp"></i>
                            Visita nuestro Whatsapp
                        </p>
                    </a>
                    <a class="text-decoration-none" target="_blank"
                        href="mailto:labcdm.12@gmail.com?subject=Consulta%20de%20examen&body=Hola%20estoy%20interesado%20en%20un%20examen">
                        <p class="text-white text-center">
                            <i class="bi bi-envelope-at"></i>
                            Visita nuestro correo Gmail
                        </p>
                    </a>

                </div>
                <div class="col d-flex flex-column justify-content-center align-items-center">
                    <p class="text-white">Desarrollado por </p>
                    <a class="text-decoration-none text-white" target="_blank"
                        href="https://www.instagram.com/im_danieldev/">
                        <p> Dickson vejar</p>
                    </a>
                    <a class="text-decoration-none text-white" target="_blank"
                        href="https://www.instagram.com/deiby_vejar/">
                        <p> Deiby vejar</p>
                    </a>
                    <a class="text-decoration-none text-white" target="_blank"
                        href="https://www.instagram.com/deiby_vejar/">
                        <p> Maria Rosa</p>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <!-- Script modo oscuro y fecha/hora -->
    <script src="{% static 'app2/js/index.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>